name: parking_finder_app
description: A Flutter application for finding nearby parking spots
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  http: ^1.1.0
  geolocator: ^10.0.0
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true